Less crude way to bump patches

diff --git a/.github/workflows/tag-patches.yml b/.github/workflows/tag-patches.yml
--- a/.github/workflows/tag-patches.yml
+++ b/.github/workflows/tag-patches.yml
@@ -18,9 +18,21 @@ jobs:
       - name: Tag new version
         run: |
           BASE_VERSION="2.20"
-          PATCH_VERSION_OFFSET=101
 
-          PATCH_VERSION=$(($GITHUB_RUN_NUMBER-$PATCH_VERSION_OFFSET))
+          PREVIOUS_TAG=$(git tag --list | awk -v s="$BASE_VERSION." 'index($0, s) == 1' | sort -r --version-sort | head -n1)
+          echo "Previous tag is $PREVIOUS_TAG"
+          PREVIOUS_PATCH=$(echo "$PREVIOUS_TAG" | cut -d. -f3)
+
+          regex='^[0-9]+$'
+          if [[ "$PREVIOUS_PATCH" =~ ^[0-9]+$ ]]; then
+            PATCH_VERSION="$(($PREVIOUS_PATCH+1))"
+          elif [[ "$PREVIOUS_PATCH" == "" ]]; then
+            PATCH_VERSION="0"
+          else
+            echo "Can't calculate next patch number from tag $PREVIOUS_TAG"
+            exit 1
+          fi
+
           FULL_VERSION="$BASE_VERSION.$PATCH_VERSION"
 
           echo "Tagging version $FULL_VERSION"
